apiVersion: v2
name: operational-requests
description: Componentes propios de la plataforma de solicitudes operacionales
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - spring-boot
  - react
  - microfrontend
