package co.com.operationalrequests.indicators.application;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import com.fasterxml.jackson.databind.ObjectMapper; import java.util.concurrent.atomic.AtomicInteger; import org.junit.jupiter.api.*; import org.junit.jupiter.params.ParameterizedTest; import org.junit.jupiter.params.provider.ValueSource; import org.springframework.dao.DuplicateKeyException; import org.springframework.jdbc.core.JdbcTemplate;
class AnalyticsServiceTest {
 JdbcTemplate jdbc; AnalyticsService service; AtomicInteger processed;
 @BeforeEach void setUp(){jdbc=mock(JdbcTemplate.class);service=new AnalyticsService(jdbc,new ObjectMapper().findAndRegisterModules());processed=new AtomicInteger();doAnswer(i->{String sql=i.getArgument(0);if(sql.startsWith("INSERT INTO processed_event")&&processed.incrementAndGet()>1)throw new DuplicateKeyException("duplicate");return 1;}).when(jdbc).update(anyString(),any(Object[].class));when(jdbc.queryForObject(contains("category_key FROM"),eq(Long.class),any(Object[].class))).thenReturn(10L);when(jdbc.queryForObject(contains("status_key FROM"),eq(Integer.class),any(Object[].class))).thenReturn(2);when(jdbc.queryForObject(contains("actor_role_key FROM"),eq(Integer.class),any(Object[].class))).thenReturn(2);}
 @ParameterizedTest @ValueSource(strings={"SolicitudRegistrada","SolicitudTomada","SolicitudResuelta","SolicitudCerrada"}) void supportedEventCreatesFactAndProjection(String type){assertThat(service.process(event(type,1)).result()).isEqualTo(IndicatorDtos.ProcessingResult.PROCESSED);verify(jdbc).update(startsWith("INSERT INTO fact_request_transition"),any(Object[].class));verify(jdbc).update(startsWith("MERGE request_current_state"),any(Object[].class));}
 @Test void duplicateEventDoesNotDuplicateFactOrProjection(){String json=event("SolicitudRegistrada",1);assertThat(service.process(json).result()).isEqualTo(IndicatorDtos.ProcessingResult.PROCESSED);assertThat(service.process(json).result()).isEqualTo(IndicatorDtos.ProcessingResult.DUPLICATE);verify(jdbc,times(1)).update(startsWith("INSERT INTO fact_request_transition"),any(Object[].class));verify(jdbc,times(1)).update(startsWith("MERGE request_current_state"),any(Object[].class));}
 @Test void malformedEventDoesNotTouchDatabase(){assertThatThrownBy(()->service.process("{}" )).isInstanceOf(InvalidEventException.class);verifyNoInteractions(jdbc);}
 @Test void unknownVersionIsRejectedBeforeDatabase(){assertThatThrownBy(()->service.process(event("SolicitudRegistrada",2))).isInstanceOf(InvalidEventException.class);verifyNoInteractions(jdbc);}
 private static String event(String type,int version){String status=switch(type){case "SolicitudRegistrada"->"REGISTRADA";case "SolicitudTomada"->"EN_ATENCION";case "SolicitudResuelta"->"RESUELTA";default->"CERRADA";};return """
  {"eventId":"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa","occurredAt":"2026-09-16T12:00:00Z","aggregateId":"bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb","type":"%s","version":%d,"correlationId":"cccccccc-cccc-cccc-cccc-cccccccccccc","payload":{"requestId":"bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb","readableId":"SOL-2026-000001","categoryId":"11111111-1111-1111-1111-111111111111","status":"%s","priority":"MEDIA","actorRole":"ANALISTA","occurredAt":"2026-09-16T12:00:00Z"}}
  """.formatted(type,version,status);}
}
