import { lazy, Suspense, useEffect, useState, type ReactNode } from 'react';
import { BrowserRouter, Link, Navigate, Route, Routes } from 'react-router-dom';
import { AppBar, Box, Button, Card, CardContent, Chip, Container, CssBaseline, Grid, Table, TableBody, TableCell, TableHead, TableRow, TextField, ThemeProvider, Toolbar, Typography, createTheme } from '@mui/material';
import { useSelector } from 'react-redux';
import { ApiError, createHttpClient, runtimeConfig, Summary, Trend, type AuthBridge, type Role } from '@operational/shared';
import type { RootState } from './store';
import { authBridge } from './auth';
const RequestsRoutes = lazy(() => import('requestsMfe/Routes'));
const theme = createTheme({ palette: { primary: { main: '#174a7c' } } });
function Guard({ roles, children }: { roles?: Role[]; children: ReactNode }) { const s = useSelector((x: RootState) => x.session); if (!s.initialized) return <p role="status">Recuperando sesión…</p>; if (!s.authenticated) return <Navigate to="/" replace />; if (roles && !roles.some(r => s.roles.includes(r))) return <Navigate to="/sin-autorizacion" replace />; return children; }
function Home({ auth }: { auth: AuthBridge }) { const s = useSelector((x: RootState) => x.session); return <Card><CardContent><Typography variant="h4" component="h1">Gestión operacional</Typography>{s.authenticated ? <><Typography>Sesión de {s.username ?? s.subject}</Typography><Box sx={{ display: 'flex', gap: 1, my: 2 }}>{s.roles.map(r => <Chip key={r} label={r} />)}</Box><Button component={Link} to="/solicitudes">Ir a solicitudes</Button></> : <><Typography sx={{ my: 2 }}>Inicie sesión para consultar y gestionar solicitudes.</Typography><Button variant="contained" onClick={() => void auth.login()}>Iniciar sesión</Button></>}</CardContent></Card>; }
function Indicators({ auth }: { auth: AuthBridge }) { const [data, setData] = useState<ReturnType<typeof Summary.parse>>(); const [trend, setTrend] = useState<ReturnType<typeof Trend.parse>>(); const [error, setError] = useState(''); const [dates, setDates] = useState({ desde: '', hasta: '' }); const load = async () => { setError(''); try { const get = createHttpClient(auth.authTokenProvider); const q = new URLSearchParams(Object.entries(dates).filter(([, v]) => v)); const [a, b] = await Promise.all([get(`${runtimeConfig.indicatorsApiUrl}/api/v1/indicadores/resumen`, {}, Summary), get(`${runtimeConfig.indicatorsApiUrl}/api/v1/indicadores/tendencia?${q}`, {}, Trend)]); setData(a); setTrend(b); } catch (e) { setError(e instanceof ApiError ? e.message : 'No fue posible cargar indicadores'); } }; useEffect(() => { void load(); }, []); if (error) return <Box role="alert"><Typography>{error}</Typography><Button onClick={() => void load()}>Reintentar</Button></Box>; if (!data || !trend) return <p role="status">Cargando indicadores…</p>; return <><Typography variant="h4" component="h1">Indicadores</Typography><Box component="form" onSubmit={e => { e.preventDefault(); void load(); }} sx={{ display: 'flex', gap: 2, my: 2, flexWrap: 'wrap' }}><TextField type="date" label="Desde" InputLabelProps={{ shrink: true }} value={dates.desde} onChange={e => setDates({ ...dates, desde: e.target.value })} /><TextField type="date" label="Hasta" InputLabelProps={{ shrink: true }} value={dates.hasta} onChange={e => setDates({ ...dates, hasta: e.target.value })} /><Button type="submit">Aplicar</Button></Box><Typography variant="h5">Total: {data.total}</Typography><Grid container spacing={2} sx={{ my: 1 }}>{data.porEstado.map(x => <Grid key={x.estado} size={{ xs: 12, sm: 6, md: 3 }}><Card><CardContent><strong>{x.estado.replace('_', ' ')}</strong><Typography variant="h4">{x.cantidad}</Typography></CardContent></Card></Grid>)}</Grid>{data.total === 0 ? <p>No hay indicadores todavía.</p> : <><Table size="small"><caption>Solicitudes actuales por categoría</caption><TableHead><TableRow><TableCell>Categoría</TableCell><TableCell align="right">Cantidad</TableCell></TableRow></TableHead><TableBody>{data.porCategoria.map(x => <TableRow key={x.categoriaId}><TableCell>{x.categoria}</TableCell><TableCell align="right">{x.cantidad}</TableCell></TableRow>)}</TableBody></Table><Table size="small"><caption>Tendencia diaria UTC</caption><TableHead><TableRow><TableCell>Fecha</TableCell><TableCell align="right">Registradas</TableCell></TableRow></TableHead><TableBody>{trend.puntos.map(x => <TableRow key={x.fecha}><TableCell>{x.fecha}</TableCell><TableCell align="right">{x.cantidadRegistradas}</TableCell></TableRow>)}</TableBody></Table></>}</>; }
export default function App() { const session = useSelector((x: RootState) => x.session); const auth = authBridge(session); return <ThemeProvider theme={theme}><CssBaseline /><BrowserRouter><a className="skip-link" href="#main">Saltar al contenido</a><AppBar position="static"><Toolbar sx={{ gap: 2 }}><Typography variant="h6" sx={{ flexGrow: 1 }}>Solicitudes operacionales</Typography><Button color="inherit" component={Link} to="/">Inicio</Button>{session.authenticated && <Button color="inherit" component={Link} to="/solicitudes">Solicitudes</Button>}{session.roles.some(r => r === 'ANALISTA' || r === 'SUPERVISOR') && <Button color="inherit" component={Link} to="/indicadores">Indicadores</Button>}{session.authenticated && <Button color="inherit" onClick={() => void auth.logout()}>Salir</Button>}</Toolbar></AppBar><Container id="main" component="main" sx={{ py: 4 }}><Routes><Route path="/" element={<Home auth={auth} />} /><Route path="/solicitudes/*" element={<Guard><Typography variant="overline">Módulo federado de solicitudes</Typography><Suspense fallback={<p role="status">Cargando módulo de solicitudes…</p>}><RequestsRoutes auth={auth} /></Suspense></Guard>} /><Route path="/indicadores" element={<Guard roles={['ANALISTA', 'SUPERVISOR']}><Indicators auth={auth} /></Guard>} /><Route path="/sin-autorizacion" element={<Box role="alert"><Typography variant="h4">Autorización insuficiente</Typography><Typography>Su sesión no tiene el rol requerido.</Typography></Box>} /><Route path="*" element={<Typography variant="h4">Página no encontrada</Typography>} /></Routes></Container></BrowserRouter></ThemeProvider>; }
