package co.com.operationalrequests.indicators.rest;
import static org.mockito.Mockito.*; import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import co.com.operationalrequests.indicators.application.*; import co.com.operationalrequests.indicators.security.SecurityConfig; import java.time.Instant; import java.util.*; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest; import org.springframework.boot.test.mock.mockito.MockBean; import org.springframework.context.annotation.Import; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.security.oauth2.jwt.JwtDecoder; import org.springframework.test.web.servlet.MockMvc;
@WebMvcTest(IndicatorsController.class) @Import({SecurityConfig.class,IndicatorsExceptionHandler.class}) class IndicatorsControllerTest {
 @Autowired MockMvc mvc; @MockBean AnalyticsService service; @MockBean JwtDecoder decoder;
 private static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.JwtRequestPostProcessor role(String role){return jwt().authorities(new SimpleGrantedAuthority("ROLE_"+role));}
 @Test void unauthenticatedIs401()throws Exception{mvc.perform(get("/api/v1/indicadores/resumen")).andExpect(status().isUnauthorized());}
 @Test void requesterIs403()throws Exception{mvc.perform(get("/api/v1/indicadores/resumen").with(role("SOLICITANTE"))).andExpect(status().isForbidden());}
 @Test void supervisorCanReadSummary()throws Exception{when(service.summary()).thenReturn(new IndicatorDtos.Summary(List.of(),List.of(),0,Instant.EPOCH));mvc.perform(get("/api/v1/indicadores/resumen").with(role("SUPERVISOR"))).andExpect(status().isOk()).andExpect(jsonPath("$.total").value(0));}
 @Test void analystCanReadSummaryByDocumentedDecision()throws Exception{when(service.summary()).thenReturn(new IndicatorDtos.Summary(List.of(),List.of(),0,Instant.EPOCH));mvc.perform(get("/api/v1/indicadores/resumen").with(role("ANALISTA"))).andExpect(status().isOk());}
 @Test void invalidRangeIs400()throws Exception{mvc.perform(get("/api/v1/indicadores/tendencia?desde=2026-12-31&hasta=2026-01-01").with(role("SUPERVISOR"))).andExpect(status().isBadRequest()).andExpect(jsonPath("$.errorCode").value("INVALID_DATE_RANGE"));}
}
