import { useState } from 'react';
import { Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Typography } from '@mui/material';
import type { RequestDetailType } from '@operational/shared';
export function StatusChip({ status }: { status: string }) { const colors: Record<string, 'default' | 'info' | 'warning' | 'success'> = { REGISTRADA: 'info', EN_ATENCION: 'warning', RESUELTA: 'success', CERRADA: 'default' }; return <Chip size="small" color={colors[status] ?? 'default'} label={status.replace('_', ' ')} />; }
export function PriorityChip({ priority }: { priority: string }) { return <Chip size="small" variant="outlined" label={`Prioridad ${priority}`} />; }
export function LoadingState({ label = 'Cargando…' }: { label?: string }) { return <Box role="status" sx={{ display: 'flex', gap: 2, p: 3 }}><CircularProgress size={24} /><span>{label}</span></Box>; }
export function EmptyState({ title = 'No hay resultados' }: { title?: string }) { return <Box sx={{ p: 4, textAlign: 'center' }}><Typography variant="h6">{title}</Typography><Typography>Pruebe modificando los filtros.</Typography></Box>; }
export function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) { return <Box role="alert" sx={{ p: 3 }}><Typography>{message}</Typography><Button onClick={onRetry}>Reintentar</Button></Box>; }
export function RequestTimeline({ items }: { items: RequestDetailType['historial'] }) { return <Box component="ol" aria-label="Historial de estados">{[...items].sort((a, b) => a.ocurridoEn.localeCompare(b.ocurridoEn)).map(x => <li key={x.id}><strong>{x.estadoNuevo.replace('_', ' ')}</strong> · {new Date(x.ocurridoEn).toLocaleString()} · {x.rolActor}{x.motivo && <> — {x.motivo}</>}</li>)}</Box>; }
export function ConfirmTransitionDialog({ open, title, onClose, onConfirm, requiresReason = false }: { open: boolean; title: string; onClose: () => void; onConfirm: (reason: string) => void; requiresReason?: boolean }) { const [reason, setReason] = useState(''); return <Dialog open={open} onClose={onClose}><DialogTitle>{title}</DialogTitle><DialogContent><label>Motivo {requiresReason && '(obligatorio)'}<textarea aria-label="Motivo" value={reason} onChange={e => setReason(e.target.value)} /></label></DialogContent><DialogActions><Button onClick={onClose}>Cancelar</Button><Button disabled={requiresReason && !reason.trim()} onClick={() => onConfirm(reason)}>Confirmar</Button></DialogActions></Dialog>; }
