import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, Box, Button, Card, CardContent, FormControl, InputLabel, MenuItem, Pagination, Select, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { ApiError, CreateRequest, type AuthBridge, type RequestDetailType, type RequestSummaryType } from '@operational/shared';
import { requestsApi } from './api';
import { EmptyState, ErrorState, LoadingState, PriorityChip, RequestTimeline, StatusChip } from './components';

function useLoad<T>(loader: (signal: AbortSignal) => Promise<T>, deps: unknown[]) {
  const [state, setState] = useState<{ data?: T; error?: string; loading: boolean }>({ loading: true });
  const reload = () => { const controller = new AbortController(); setState(previous => previous.data ? { data: previous.data, loading: true } : { loading: true }); void loader(controller.signal).then(data => setState({ data, loading: false })).catch(error => { if (error?.name !== 'AbortError') setState({ loading: false, error: error instanceof Error ? error.message : 'Error inesperado' }); }); return () => controller.abort(); };
  useEffect(reload, deps);
  return { ...state, reload };
}

export function InboxPage({ auth }: { auth: AuthBridge }) {
  const api = useMemo(() => requestsApi(auth.authTokenProvider), [auth.authTokenProvider]);
  const [page, setPage] = useState(0);
  const [filters, setFilters] = useState({ estado: '', categoriaId: '', prioridad: '' });
  const query = new URLSearchParams({ page: String(page), size: '20', ...Object.fromEntries(Object.entries(filters).filter(([, value]) => value)) }).toString();
  const result = useLoad(async signal => { const [categories, requests] = await Promise.all([api.categories(), api.list(query, signal)]); return { categories, requests }; }, [query]);
  const data = result.data;
  return <Box><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between"><Typography variant="h4" component="h1">Bandeja de solicitudes</Typography>{auth.session.roles.includes('SOLICITANTE') && <Button component={Link} to="/solicitudes/nueva" variant="contained">Nueva solicitud</Button>}</Stack><Stack direction={{ xs: 'column', md: 'row' }} gap={2} my={2}><FormControl sx={{ minWidth: 180 }}><InputLabel>Estado</InputLabel><Select label="Estado" value={filters.estado} onChange={e => setFilters({ ...filters, estado: e.target.value })}><MenuItem value="">Todos</MenuItem>{['REGISTRADA', 'EN_ATENCION', 'RESUELTA', 'CERRADA'].map(value => <MenuItem key={value} value={value}>{value.replace('_', ' ')}</MenuItem>)}</Select></FormControl><FormControl sx={{ minWidth: 220 }}><InputLabel>Categoría</InputLabel><Select label="Categoría" value={filters.categoriaId} onChange={e => setFilters({ ...filters, categoriaId: e.target.value })}><MenuItem value="">Todas</MenuItem>{data?.categories.map(category => <MenuItem key={category.id} value={category.id}>{category.nombre}</MenuItem>)}</Select></FormControl><FormControl sx={{ minWidth: 180 }}><InputLabel>Prioridad</InputLabel><Select label="Prioridad" value={filters.prioridad} onChange={e => setFilters({ ...filters, prioridad: e.target.value })}><MenuItem value="">Todas</MenuItem>{['BAJA', 'MEDIA', 'ALTA'].map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</Select></FormControl><Button onClick={() => { setFilters({ estado: '', categoriaId: '', prioridad: '' }); setPage(0); }}>Limpiar filtros</Button></Stack>{result.loading ? <LoadingState label="Cargando solicitudes…" /> : result.error ? <ErrorState message={result.error} onRetry={result.reload} /> : !data?.requests.content.length ? <EmptyState /> : <><Table><caption>Solicitudes encontradas</caption><TableHead><TableRow><TableCell>Número</TableCell><TableCell>Asunto</TableCell><TableCell>Estado</TableCell><TableCell>Prioridad</TableCell></TableRow></TableHead><TableBody>{data.requests.content.map((request: RequestSummaryType) => <TableRow key={request.id}><TableCell><Link to={`/solicitudes/${request.id}`}>{request.numero}</Link></TableCell><TableCell>{request.asunto}</TableCell><TableCell><StatusChip status={request.estado} /></TableCell><TableCell><PriorityChip priority={request.prioridad} /></TableCell></TableRow>)}</TableBody></Table><Pagination page={page + 1} count={data.requests.totalPages} onChange={(_, value) => setPage(value - 1)} sx={{ mt: 2 }} /></>}</Box>;
}

export function CreatePage({ auth }: { auth: AuthBridge }) {
  const api = useMemo(() => requestsApi(auth.authTokenProvider), [auth.authTokenProvider]); const navigate = useNavigate(); const [categories, setCategories] = useState<Array<{ id: string; nombre: string }>>([]); const [form, setForm] = useState({ asunto: '', descripcion: '', categoriaId: '', prioridad: 'MEDIA' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { void api.categories().then(setCategories).catch(reason => setError(reason instanceof Error ? reason.message : 'No fue posible consultar categorías')); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (busy) return; const parsed = CreateRequest.safeParse(form); if (!parsed.success) { setError('Revise los campos obligatorios y sus longitudes.'); return; } setBusy(true); try { const created = await api.create(parsed.data); navigate(`/solicitudes/${created.id}`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible crear'); } finally { setBusy(false); } };
  return <Box component="form" onSubmit={submit} noValidate maxWidth={700}><Typography variant="h4" component="h1">Nueva solicitud</Typography>{error && <Alert severity="error" role="alert">{error}</Alert>}<TextField fullWidth required label="Asunto" margin="normal" value={form.asunto} onChange={e => setForm({ ...form, asunto: e.target.value })} /><TextField fullWidth required multiline minRows={4} label="Descripción" margin="normal" value={form.descripcion} onChange={e => setForm({ ...form, descripcion: e.target.value })} /><FormControl fullWidth required margin="normal"><InputLabel>Categoría</InputLabel><Select label="Categoría" value={form.categoriaId} onChange={e => setForm({ ...form, categoriaId: e.target.value })}>{categories.map(category => <MenuItem key={category.id} value={category.id}>{category.nombre}</MenuItem>)}</Select></FormControl><FormControl fullWidth margin="normal"><InputLabel>Prioridad</InputLabel><Select label="Prioridad" value={form.prioridad} onChange={e => setForm({ ...form, prioridad: e.target.value })}>{['BAJA', 'MEDIA', 'ALTA'].map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</Select></FormControl><Button disabled={busy} type="submit" variant="contained">{busy ? 'Creando…' : 'Crear solicitud'}</Button></Box>;
}

export function DetailPage({ auth }: { auth: AuthBridge }) {
  const { id = '' } = useParams(); const api = useMemo(() => requestsApi(auth.authTokenProvider), [auth.authTokenProvider]); const state = useLoad(signal => api.detail(id, signal), [id]); const [feedback, setFeedback] = useState('');
  const action = async (operation: () => Promise<RequestDetailType>) => { setFeedback(''); try { await operation(); setFeedback('Acción completada'); state.reload(); } catch (error) { setFeedback(error instanceof ApiError && error.status === 409 ? 'Otro analista ya tomó esta solicitud.' : error instanceof Error ? error.message : 'No fue posible completar la acción'); } };
  if (state.loading) return <LoadingState label="Recuperando sesión y solicitud…" />;
  if (state.error || !state.data) return <ErrorState message={state.error ?? 'Solicitud no encontrada'} onRetry={state.reload} />;
  const request = state.data; const analyst = auth.session.roles.includes('ANALISTA'); const supervisor = auth.session.roles.includes('SUPERVISOR'); const mine = request.analistaAsignadoId === auth.session.subject;
  return <><Typography variant="h4" component="h1">{request.numero}</Typography>{feedback && <Alert severity="info" role="status">{feedback}</Alert>}<Card sx={{ my: 2 }}><CardContent><Typography variant="h6">{request.asunto}</Typography><Typography>{request.descripcion}</Typography><Stack direction="row" gap={1} my={2}><StatusChip status={request.estado} /><PriorityChip priority={request.prioridad} /></Stack><Typography>Categoría: {request.categoriaNombre ?? 'Categoría no disponible'}</Typography><Typography>Analista asignado: {request.analistaAsignadoId ?? 'Sin asignar'}</Typography></CardContent></Card>{analyst && request.estado === 'REGISTRADA' && <Button variant="contained" onClick={() => void action(() => api.assign(request.id))}>Tomar solicitud</Button>}{analyst && mine && request.estado === 'EN_ATENCION' && <><Button onClick={() => { const texto = prompt('Observación') ?? ''; if (texto) void action(() => api.observe(request.id, { texto })); }}>Agregar observación</Button><Button onClick={() => void action(() => api.transition(request.id, { estadoDestino: 'RESUELTA', observacion: 'Resolución registrada' }))}>Resolver</Button></>}{supervisor && request.estado === 'RESUELTA' && <><Button onClick={() => { const motivo = prompt('Motivo de devolución') ?? ''; if (motivo) void action(() => api.transition(request.id, { estadoDestino: 'EN_ATENCION', motivo })); }}>Devolver</Button><Button onClick={() => { const motivo = prompt('Motivo de cierre') ?? ''; if (motivo) void action(() => api.transition(request.id, { estadoDestino: 'CERRADA', motivo })); }}>Cerrar</Button></>}<Typography variant="h5" sx={{ mt: 3 }}>Observaciones</Typography>{request.observaciones.length ? <ul>{request.observaciones.map(observation => <li key={observation.id}>{observation.texto} — {observation.rolActor}</li>)}</ul> : <EmptyState title="Sin observaciones" />}<Typography variant="h5">Historial</Typography><RequestTimeline items={request.historial} /></>;
}
