package co.com.operationalrequests.indicators.config;
import org.apache.kafka.common.TopicPartition; import org.apache.kafka.clients.admin.NewTopic; import org.slf4j.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.boot.autoconfigure.kafka.ConcurrentKafkaListenerContainerFactoryConfigurer; import org.springframework.context.annotation.*; import org.springframework.kafka.config.*; import org.springframework.kafka.core.*; import org.springframework.kafka.listener.*; import org.springframework.util.backoff.FixedBackOff;
@Configuration @Profile("!test") public class KafkaConsumerConfig {
 private static final Logger log=LoggerFactory.getLogger(KafkaConsumerConfig.class);
 @Bean NewTopic eventsTopic(@Value("${events.topic:operational-requests.events.v1}")String topic){return TopicBuilder.name(topic).partitions(3).replicas(1).build();}
 @Bean NewTopic eventsDltTopic(@Value("${events.dlt-topic:operational-requests.events.v1.dlt}")String topic){return TopicBuilder.name(topic).partitions(3).replicas(1).build();}
 @Bean DefaultErrorHandler eventsErrorHandler(KafkaTemplate<String,String> kafka,@Value("${events.dlt-topic:operational-requests.events.v1.dlt}")String dlt){var recoverer=new DeadLetterPublishingRecoverer(kafka,(record,ex)->{log.error("Evento enviado a DLT topic={} partition={} offset={} error={}",dlt,record.partition(),record.offset(),ex.getClass().getSimpleName());return new TopicPartition(dlt,record.partition());});return new DefaultErrorHandler(recoverer,new FixedBackOff(1000,2));}
 @Bean ConcurrentKafkaListenerContainerFactory<Object,Object> eventsKafkaListenerContainerFactory(ConcurrentKafkaListenerContainerFactoryConfigurer configurer,ConsumerFactory<Object,Object> consumerFactory,DefaultErrorHandler handler,@Value("${events.concurrency:1}")int concurrency){var factory=new ConcurrentKafkaListenerContainerFactory<Object,Object>();configurer.configure(factory,consumerFactory);factory.setCommonErrorHandler(handler);factory.getContainerProperties().setAckMode(ContainerProperties.AckMode.MANUAL_IMMEDIATE);factory.setConcurrency(concurrency);return factory;}
}
