package co.com.operationalrequests.requests.infrastructure.adapter.in.rest;
import co.com.operationalrequests.requests.domain.exception.*; import jakarta.servlet.http.HttpServletRequest; import java.time.Instant;
import org.springframework.dao.OptimisticLockingFailureException; import org.springframework.http.*; import org.springframework.web.bind.MethodArgumentNotValidException; import org.springframework.web.bind.annotation.*; import org.springframework.web.method.annotation.MethodArgumentTypeMismatchException;
import org.springframework.http.converter.HttpMessageNotReadableException; import jakarta.validation.ConstraintViolationException;
@RestControllerAdvice public class GlobalExceptionHandler {
 @ExceptionHandler(SolicitudNoEncontradaException.class) ProblemDetail notFound(Exception e,HttpServletRequest r){return problem(HttpStatus.NOT_FOUND,"Recurso no encontrado",e.getMessage(),"REQUEST_NOT_FOUND",r);}
 @ExceptionHandler(CategoriaNoDisponibleException.class) ProblemDetail category(Exception e,HttpServletRequest r){return problem(HttpStatus.UNPROCESSABLE_ENTITY,"Categoría no disponible",e.getMessage(),"CATEGORY_UNAVAILABLE",r);}
 @ExceptionHandler({ConflictoAsignacionException.class,OptimisticLockingFailureException.class}) ProblemDetail conflict(Exception e,HttpServletRequest r){return problem(HttpStatus.CONFLICT,"Conflicto de concurrencia","La solicitud fue modificada por otra operación","CONCURRENT_MODIFICATION",r);}
 @ExceptionHandler(TransicionEstadoInvalidaException.class) ProblemDetail transition(Exception e,HttpServletRequest r){return problem(HttpStatus.UNPROCESSABLE_ENTITY,"Transición inválida",e.getMessage(),"INVALID_TRANSITION",r);}
 @ExceptionHandler(AccesoDominioNoPermitidoException.class) ProblemDetail forbidden(Exception e,HttpServletRequest r){return problem(HttpStatus.FORBIDDEN,"Acceso no permitido",e.getMessage(),"FORBIDDEN_OPERATION",r);}
 @ExceptionHandler({MethodArgumentNotValidException.class,MethodArgumentTypeMismatchException.class,HttpMessageNotReadableException.class,ConstraintViolationException.class,IllegalArgumentException.class}) ProblemDetail badRequest(Exception e,HttpServletRequest r){return problem(HttpStatus.BAD_REQUEST,"Solicitud inválida","Revise los parámetros y campos enviados","VALIDATION_ERROR",r);}
 private static ProblemDetail problem(HttpStatus status,String title,String detail,String code,HttpServletRequest request){var p=ProblemDetail.forStatusAndDetail(status,detail);p.setTitle(title);p.setType(java.net.URI.create("urn:problem:operational-requests:"+code.toLowerCase()));p.setInstance(java.net.URI.create(request.getRequestURI()));p.setProperty("errorCode",code);p.setProperty("correlationId",String.valueOf(request.getAttribute(CorrelationIdFilter.ATTRIBUTE)));p.setProperty("timestamp",Instant.now());return p;}
}
