package co.com.operationalrequests.requests.application.usecase;
import co.com.operationalrequests.requests.application.command.*; import co.com.operationalrequests.requests.application.port.out.*; import co.com.operationalrequests.requests.domain.exception.*; import co.com.operationalrequests.requests.domain.model.*;
import java.time.Instant; import java.util.*; import org.junit.jupiter.api.*; import org.mockito.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
class RequestsApplicationServiceTest {
 @Mock CategoriaRepositoryPort categories; @Mock SolicitudRepositoryPort requests; @Mock OutboxPort outbox; @Mock RequestNumberPort numbers; @Mock ClockPort clock;
 RequestsApplicationService service; Instant now=Instant.parse("2026-01-01T12:00:00Z"); UUID category=UUID.randomUUID(),requester=UUID.randomUUID(),analyst=UUID.randomUUID();
 @BeforeEach void setUp(){MockitoAnnotations.openMocks(this);service=new RequestsApplicationService(categories,requests,outbox,numbers,clock);when(clock.now()).thenReturn(now);}
 ActorActual actor(UUID id,RolActor role){return new ActorActual(id,role.name().toLowerCase(),Set.of(role));}
 Solicitud reconstructed(EstadoSolicitud state,UUID assigned){return Solicitud.reconstruir(UUID.randomUUID(),"SOL-2026-000001","Asunto",category,requester,Prioridad.MEDIA,"Descripción",state,assigned,now,now,1,List.of(),List.of());}
 @Test void validCreationPreparesHistoryAndOutbox(){when(categories.findActiveById(category)).thenReturn(Optional.of(new Categoria(category,"G","General")));when(numbers.next(now)).thenReturn("SOL-2026-000001");when(requests.save(any())).thenAnswer(i->i.getArgument(0));var result=service.create(new CrearSolicitudCommand("Asunto","Descripción",category,Prioridad.MEDIA,actor(requester,RolActor.SOLICITANTE),UUID.randomUUID()));assertThat(result.estado()).isEqualTo(EstadoSolicitud.REGISTRADA);assertThat(result.historial()).hasSize(1);verify(outbox).append(any(),eq(result.id()),eq("SolicitudRegistrada"),eq(1),any(),eq(now),anyMap());}
 @Test void inactiveCategoryRejectsWithoutPersistence(){when(categories.findActiveById(category)).thenReturn(Optional.empty());assertThatThrownBy(()->service.create(new CrearSolicitudCommand("A","D",category,Prioridad.MEDIA,actor(requester,RolActor.SOLICITANTE),UUID.randomUUID()))).isInstanceOf(CategoriaNoDisponibleException.class);verifyNoInteractions(requests,outbox);}
 @Test void detailKeepsCategoryIdAndAddsCategoryName(){var r=reconstructed(EstadoSolicitud.REGISTRADA,null);when(requests.findDetailById(r.id())).thenReturn(Optional.of(r));when(categories.findActiveById(category)).thenReturn(Optional.of(new Categoria(category,"GENERAL","General")));var result=service.detail(r.id(),actor(requester,RolActor.SOLICITANTE));assertThat(result.categoriaId()).isEqualTo(category);assertThat(result.categoriaNombre()).isEqualTo("General");}
 @Test void requesterCannotCloseAndNothingIsPersisted(){var command=new TransicionarSolicitudCommand(UUID.randomUUID(),EstadoSolicitud.CERRADA,"motivo",null,actor(requester,RolActor.SOLICITANTE),UUID.randomUUID());when(requests.findDetailById(command.solicitudId())).thenReturn(Optional.of(reconstructed(EstadoSolicitud.RESUELTA,analyst)));assertThatThrownBy(()->service.transition(command)).isInstanceOf(AccesoDominioNoPermitidoException.class);verify(requests,never()).save(any());verifyNoInteractions(outbox);}
 @Test void unassignedAnalystCannotResolve(){var r=reconstructed(EstadoSolicitud.EN_ATENCION,analyst);when(requests.findDetailById(r.id())).thenReturn(Optional.of(r));var cmd=new TransicionarSolicitudCommand(r.id(),EstadoSolicitud.RESUELTA,null,null,actor(UUID.randomUUID(),RolActor.ANALISTA),UUID.randomUUID());assertThatThrownBy(()->service.transition(cmd)).isInstanceOf(AccesoDominioNoPermitidoException.class);verify(requests,never()).save(any());}
 @Test void conditionalAssignmentAllowsOnlyWinner(){var registered=reconstructed(EstadoSolicitud.REGISTRADA,null);var assigned=reconstructed(EstadoSolicitud.EN_ATENCION,analyst);when(requests.findDetailById(registered.id())).thenReturn(Optional.of(registered),Optional.of(assigned),Optional.of(assigned));when(requests.assignIfRegistered(eq(registered.id()),eq(analyst),eq(now))).thenReturn(true,false);var a=actor(analyst,RolActor.ANALISTA);service.assign(registered.id(),a,UUID.randomUUID());assertThatThrownBy(()->service.assign(registered.id(),a,UUID.randomUUID())).isInstanceOf(ConflictoAsignacionException.class);verify(requests,times(2)).assignIfRegistered(eq(registered.id()),eq(analyst),eq(now));verify(outbox,times(1)).append(any(),any(),eq("SolicitudTomada"),anyInt(),any(),any(),anyMap());}
 @Test void supervisorCanReturnWithReason(){var r=reconstructed(EstadoSolicitud.RESUELTA,analyst);when(requests.findDetailById(r.id())).thenReturn(Optional.of(r));when(requests.save(any())).thenAnswer(i->i.getArgument(0));var result=service.transition(new TransicionarSolicitudCommand(r.id(),EstadoSolicitud.EN_ATENCION,"Revisar",null,actor(UUID.randomUUID(),RolActor.SUPERVISOR),UUID.randomUUID()));assertThat(result.estado()).isEqualTo(EstadoSolicitud.EN_ATENCION);assertThat(result.historial().getLast().motivo()).isEqualTo("Revisar");verifyNoInteractions(outbox);}
 @Test void supervisorCanCloseAndCreatesEvent(){var r=reconstructed(EstadoSolicitud.RESUELTA,analyst);when(requests.findDetailById(r.id())).thenReturn(Optional.of(r));when(requests.save(any())).thenAnswer(i->i.getArgument(0));service.transition(new TransicionarSolicitudCommand(r.id(),EstadoSolicitud.CERRADA,"Aprobada",null,actor(UUID.randomUUID(),RolActor.SUPERVISOR),UUID.randomUUID()));verify(outbox).append(any(),eq(r.id()),eq("SolicitudCerrada"),eq(1),any(),eq(now),anyMap());}
}
